import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <header class="main-header">
        <div class="container">
            <a class="logo">RGK.code</a>
            <nav class="main-nav">
                <ul>
                    <li><a href="#hero">Who We Are</a></li>
                    <li><a href="#skills">Online Stores</a></li>
                    <li><a href="#acquaintances">Acquaintances</a></li>
                    <li><a href="#history">Our History</a></li>
                    <li><a href="#services">Our Services</a></li>
                    <li><a href="#contact">Contact Us</a></li>
                </ul>
            </nav>
            <div class="menu-toggle" id="mobile-menu">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </header>
        {children}
         <footer id="contact" class="contact-section">
        <div class="container">
            <h2>Contact Us</h2>
            <p>For collaboration and a free consultation, get in touch with us.</p>
            <div class="contact-info">
                <div class="contact-item">
                    <i class="fas fa-envelope"></i>
                    <a href="mailto:info@rgk.code">info@rgk.code</a>
                </div>
                <div class="contact-item">
                    <i class="fas fa-phone"></i>
                    <a href="tel:+989937827724">+98 993 782 7724</a>
                </div>
                 <div class="contact-item">
                    <i class="fab fa-telegram-plane"></i>
                    <a href="https://t.me/reza_ghazi_696" target="_blank">@yourusername</a>
                </div>
            </div>
            <div class="social-links">
                <a href="#" target="_blank" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                <a href="#" target="_blank" aria-label="GitHub"><i class="fab fa-github"></i></a>
                <a href="#" target="_blank" aria-label="Instagram"><i class="fab fa-instagram"></i></a>
            </div>
            <p class="copyright">&copy; 2024 RGK.code. All Rights Reserved.</p>
        </div>
    </footer>
      </body>
    </html>
  );
}
